name: Deploy Python API to Azure Web App

env:
  AZURE_WEBAPP_NAME: my-simple-flask-api-one
  # Replace with your app name
  PYTHON_VERSION: '3.8'

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Create virtual environment and install dependencies
      run: |
        python - <<EOF
        import venv
        import subprocess
        import sys

        def create_venv_and_install():
            venv.create('venv', with_pip=True)
            
            # Determine the pip path
            if sys.platform == 'win32':
                pip_path = r'venv\Scripts\pip'
            else:
                pip_path = 'venv/bin/pip'
            
            # Install dependencies
              pip install -r requirements.txt

        if __name__ == "__main__":
            create_venv_and_install()
        EOF

    - name: Check code style
      run: |
        pip install flake8
        python - <<EOF
        import subprocess

        def check_style():
            result = subprocess.run(['flake8', '.'], capture_output=True, text=True)
            if result.returncode != 0:
                print("Style check failed:")
                print(result.stdout)
                exit(1)
            else:
                print("Style check passed!")

        if __name__ == "__main__":
            check_style()
        EOF

    - name: Run application (for testing)
      run: |
        python - <<EOF
        import subprocess
        import time

        def run_app():
            process = subprocess.Popen(['python', 'main.py'])
            time.sleep(5)  # Give the app some time to start
            process.terminate()

        if __name__ == "__main__":
            run_app()
        EOF

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        
